services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: _9rGfw6nM-Cbv_Twnywx
      MYSQL_DATABASE: dev
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend: