spring:
  application:
    name: bachelor-grpc-api

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:dev}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:devuser}
    password: ${DB_PASSWORD:devpass123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

grpc:
  server:
    port: ${PORT:9091}
    reflection-service-enabled: true

jwt:
  secret_key: ${JWT_KEY:YouAndIJudasEffectSpineLittleDarkAgesKnockAtMyDoor}
